### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by mahipalsingh-syt** [Soomgo-Mobile/react-native-animated-pagination-dot#28]
error ```nano-css detected browser environment because of "window" global, but "document" global seems to be defective.```

import PaginationDot from "react-native-animated-pagination-dot"
<PaginationDot activeDotColor={colors.green10} curPage={0} maxPage={6} />

Language : typescript 
RN : 0.63.4

**Comment by sportsjay** [comment]
I am experiencing the same thing:

Here's my error logs for reference

```console
nano-css detected browser environment because of "window" global, but "document" global seems to be defective.
at node_modules\react-native\Libraries\LogBox\LogBox.js:148:8 in registerError
at node_modules\react-native\Libraries\LogBox\LogBox.js:59:8 in errorImpl
at node_modules\react-native\Libraries\LogBox\LogBox.js:33:4 in console.error
at node_modules\expo\build\environment\react-native-logs.fx.js:27:4 in error
at node_modules\nano-css\index.js:21:24 in exports.create
at http://192.168.0.102:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:182835:30 in <unknown>       
at node_modules\metro\src\lib\polyfills\require.js:321:11 in loadModuleImplementation
at http://192.168.0.102:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:179740:28 in <unknown>       
at node_modules\metro\src\lib\polyfills\require.js:321:11 in loadModuleImplementation
at http://192.168.0.102:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:179476:29 in <unknown>       
at node_modules\metro\src\lib\polyfills\require.js:321:11 in loadModuleImplementation
at http://192.168.0.102:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:179277:47 in <unknown>       
at node_modules\metro\src\lib\polyfills\require.js:321:11 in loadModuleImplementation
at http://192.168.0.102:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:179056:76 in <unknown>       
at node_modules\metro\src\lib\polyfills\require.js:321:11 in loadModuleImplementation
at app\main\routes\routes.tsx:3:0 in <global>
at node_modules\metro\src\lib\polyfills\require.js:321:11 in loadModuleImplementation
at app\main\navigations\index.tsx:6:0 in <global>
at node_modules\metro\src\lib\polyfills\require.js:321:11 in loadModuleImplementation
at app\main\index.tsx:3:0 in <global>
at node_modules\metro\src\lib\polyfills\require.js:321:11 in loadModuleImplementation
at App.tsx:4:0 in <global>
at node_modules\metro\src\lib\polyfills\require.js:321:11 in loadModuleImplementation
at node_modules\expo\AppEntry.js:3:0 in <global>
at node_modules\metro\src\lib\polyfills\require.js:321:11 in loadModuleImplementation
at node_modules\metro\src\lib\polyfills\require.js:201:44 in guardedLoadModule
at http://192.168.0.102:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:189943:3 in global code      

ReferenceError: Can't find variable: document
at node_modules\react-native\Libraries\LogBox\LogBox.js:148:8 in registerError
at node_modules\react-native\Libraries\LogBox\LogBox.js:59:8 in errorImpl
at node_modules\react-native\Libraries\LogBox\LogBox.js:33:4 in console.error
at node_modules\expo\build\environment\react-native-logs.fx.js:27:4 in error
at node_modules\react-native\Libraries\Core\ExceptionsManager.js:104:6 in reportException
at node_modules\react-native\Libraries\Core\ExceptionsManager.js:171:19 in handleException
at node_modules\react-native\Libraries\Core\setUpErrorHandling.js:24:6 in handleError
at node_modules\expo-error-recovery\build\ErrorRecovery.fx.js:12:21 in ErrorUtils.setGlobalHandler$argument_0
at node_modules\regenerator-runtime\runtime.js:63:36 in tryCatch
at node_modules\regenerator-runtime\runtime.js:294:29 in invoke
at node_modules\regenerator-runtime\runtime.js:63:36 in tryCatch
at node_modules\regenerator-runtime\runtime.js:155:27 in invoke
at node_modules\regenerator-runtime\runtime.js:165:18 in PromiseImpl.resolve.then$argument_0
at node_modules\react-native\node_modules\promise\setimmediate\core.js:37:13 in tryCallOne
at node_modules\react-native\node_modules\promise\setimmediate\core.js:123:24 in setImmediate$argument_0
at node_modules\react-native\Libraries\Core\Timers\JSTimers.js:130:14 in _callTimer
at node_modules\react-native\Libraries\Core\Timers\JSTimers.js:181:14 in _callImmediatesPass
at node_modules\react-native\Libraries\Core\Timers\JSTimers.js:441:30 in callImmediates
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:387:6 in __callImmediates
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:135:6 in __guard$argument_0
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:364:10 in __guard
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:134:4 in flushedQueue
```

**Comment by vyarmak** [comment]
According to https://github.com/streamich/react-use/issues/483 this can be fixed by changing `src/component/Dot.tsx`:

```
- import { usePrevious } from 'react-use';
+ import usePrevious from 'react-use/lib/usePrevious';
```

Suggested change in #29

**Comment by sospedra** [comment]
Not worth adding `react-use` for just one simple hook

**Comment by pratt3351** [comment]
hi, its fixed here !

https://github.com/Soomgo-Mobile/react-native-animated-pagination-dot/pull/29
